### ISSUE TITLE
PMXML tasks are all critical

### ISSUE THREAD

**Issue by lironzluf** [joniles/mpxj#206] opened 2021-02-02 19:14 UTC
When importing this specific PMXML Schedule, all tasks are marked critical.
When importing the same schedule in XER format, the tasks critical field is set correctly.

![image](https://user-images.githubusercontent.com/19565529/106650404-89baf780-659b-11eb-8dfc-1d35297e0bd1.png)

[CM007 V14.xml.zip](https://github.com/joniles/mpxj/files/5913915/CM007.V14.xml.zip)

**Comment by VipulADSK** [comment] 2021-03-12 06:53
I see that this is observed on XER file as well. From what I saw in the file Schedule Option, I learnt that these kind of Schedule are Scheduled (Critical Path Calculated) using 'Longest Path' method and not through 'Total float less than or equal to' method in Primavera and if we Schedule them using 'Total Float' method, Primavera marks every task/activity as Critical.

So I am just curious if we are taking into consideration the scenarios were the Schedules are calculated by 'Longest Path' method instead of 'Total Float' in MPXJ.

**Comment by joniles** [comment] 2021-03-16 09:15
@VipulADSK could you attach an example XER file which exhibits this behaviour? Thanks!

**Comment by VipulADSK** [comment] 2021-03-16 09:33
@joniles Please find the files as attachment (XER, XML and PDF). I have also printed the File in PDF from P6 if required.

[CM007 V14.zip](https://github.com/joniles/mpxj/files/6147645/CM007.V14.zip)

**Comment by joniles** [comment] 2021-03-22 19:08
Thanks for providing the files. As you suspected the issue is that MPXJ is assuming the "total float" method for determining critical activities, and so gets it wrong when "longest path" has been selected.

Unfortunately at present I haven't implemented the code to  calculate the longest path, so MPXJ doesn't have the information it needs to correctly set the critical flag in this situation. As a workaround for now, if MPXJ determines that "longest path" has been selected in the schedule for calculating the critical activities, MPXJ will default the value of the critical flag to false for all activities. The changes for this will be in the next MPXJ release.

I will look into implementing the logic to support correctly setting this attribute in future.

**Closed by joniles** 2021-03-22 19:08 UTC
