### ISSUE TITLE
Iterating through Custom Fields in .net

### ISSUE THREAD

**Issue by fdahlberg** [joniles/mpxj#184] opened 2020-09-18 08:38 UTC
Hi,

I'm using mpxj in a .net environment. 

To iterate through the collections in a project such as tasks and links I've been using the following type of code:
```
var tasks = mpxjProject.Tasks.ToIEnumerable<net.sf.mpxj.Task>().ToList();
foreach (var mpxjActivity in tasks)
{ ...}
```

For some reason this doesn't seem to work for Custom Fields. Is there a specific reason for this and how should I do to iterate that collection?

Kind Regards
Fredrik Dahlberg

**Comment by joniles** [comment] 2020-09-18 10:12
Can you give me an example of the code you're trying to write (event if it doesn't compile/run), so I can get an idea of the methods you are calling?

**Comment by fdahlberg** [comment] 2020-09-18 11:05
Hi,

This is an example of code that doesn't work.

`var customFields = mpxjProject.CustomFields.ToIEnumerable<net.sf.mpxj.Task>().ToList();`

I'm just trying to understand why that doesn't work but it works with for example Tasks.

**Comment by joniles** [comment] 2020-09-18 11:52
Thanks for the update. The issue is that the extension method was written to work with classes derived from `Collection`, but the `CustomFieldContainer` is derived from `Iterable`. I've updated the extension method definitions to work with `Iterable`: https://github.com/joniles/mpxj/blob/master/src.net/MpxjUtilities/MpxjExtensionMethods.cs#L16-L48 this will be part of the next MPXJ release. Not sure if you can override the original definitions in the meantime so you can make use of the new versions, or add versions specific to `CustomFieldContainer` as a temporary workaround?

**Closed by joniles** 2020-09-18 11:52 UTC

**Comment by fdahlberg** [comment] 2020-09-18 11:54
Sounds great!

I managed to find a work around for now:

```
                var customFieldsIterator = mpxjProject.CustomFields.Iterator();
                while (customFieldsIterator.hasNext())
                {
                    var customField = (CustomField)customFieldsIterator.next();
```

**Comment by fdahlberg** [comment] 2020-10-29 10:48
Hi,
I've just updated to the latest version (8.3.2) and now I can't get this working. Not using the iterator as in my workaround or using ToIEnumerable. It behaves in a way I can't really understand. 
This is my code:

 `var allCustomFields = _wizardData.MPXJProjects.SelectMany(p => p.CustomFields.ToIEnumerable<CustomField>()).ToList();
` 
MPXJProjects is of type List<ProjectFile>

If I just step past this "allCustomFields" will be empty. But, if I hover over it in Visual studio, like this:
![image](https://user-images.githubusercontent.com/9571179/97558244-2473cb00-19dc-11eb-960c-e216f5ced18b.png)
And then step past it the list is populated... 
I haven't had this kind of issue with other collections in mpxj. Does this make any sense? It seems like the CustomFields is not evaluated until I expand it in the visual studio editor...

**Comment by joniles** [comment] 2020-11-10 10:22
Hi, sorry for the delay in replying.

I'd added some sample code to exercise the updated method when I originally made the change. It's part of the `MpxjQuery` utility: https://github.com/joniles/mpxj/blob/master/src.net/MpxjQuery/MpxjQuery.cs#L419.

I've just run this locally OK. The only difference I can see is that I'm using `file.CustomFields.ToIEnumerable()` whereas your code looks more like `file.CustomFields.ToIEnumerable<CustomField>()` although I've tried that locally too. I wonder if you `SelectMany` call isn't working as expected? Perhaps break apart the statements to get a closer look at the intermediate results.

**Comment by fdahlberg** [comment] 2020-11-10 15:49
Hi Jon,
I've already tried breaking it down in many ways. There seems to be several issues at play here. 
I just tried it again and I noticed that only fields that have an alias are returned by CustomFields. Is this by design? When I look in the xml file (attached) I can see that only the custom fields I've renamed have an alias. 
![image](https://user-images.githubusercontent.com/9571179/98696025-97355c80-2373-11eb-9299-f5bf979e97d4.png)

The situation I described before where if I hover over the objects in visual studio i can see all the custom fields only seems to happen for .mpp files. I've attached the .mpp version of the file as well.

Let me know if you need any more info.

Fred


[Activity Uncertainty Test MPP.zip](https://github.com/joniles/mpxj/files/5518436/Activity.Uncertainty.Test.MPP.zip)




[Activity Uncertainty Test.zip](https://github.com/joniles/mpxj/files/5518399/Activity.Uncertainty.Test.zip)

**Comment by joniles** [comment] 2020-11-17 16:56
Hello! Let's see if we can untangle these issues.

First, regarding which fields you should see in the custom field list. For files from MS Project, all of the custom fields exist all of the time (e.g Text1, Number1 etc), and a `CustomField` instance will be generated for you for each of these fields if you try to reference it. For example, if you just create a simple MPP file and don't make any changes to the custom fields, when you read the file you should be able to do this:

```java
projectFile.getCustomFields().getCustomField(TaskField.TEXT1)
```

This will return a `CustomField` instance for you, which it has just created. The `CustomFieldsContainer` isn't pre-populated with these fields, so it will be empty until you try to retrieve a `CustomField` instance. The only time there will be values in this container is if you have specified an alias for the field, in which case there will already be an entry in the `CustomFieldsContainer` when the file is read. I wonder if this explains the behaviour you are seeing?

If the schedule file comes from a different application, such as P6, custom fields don't exist unless a user has defined them in the application, so the `CustomFieldsContainer` will always contain all of the custom fields in use in the schedule when the schedule is loaded, regardless of whether an alias has been set.

For MS Project files, if it's helpful for you to iterate through the various custom fields, the `TaskFieldLists`, `ResourceFieldLists`, and `AssignmentFieldLists` classes have arrays which collect together the various types of custom fields for each entity. These could be used to iterate through `CustomFieldsContainer` to fully populate it if that's helpful to you?

**Comment by fdahlberg** [comment] 2020-11-18 10:28
Hi Jon,

Thanks a lot for your explanation. It seems like I've misunderstood how Custom Fields work in mpxj. 
What I want to get, is a list of all the task custom fields that are "in use". When I say "in use", I mean that some task has a value for that field. I thought I could get that list from ProjectFile.GetCustomFields, but I see now that it doesn't work like that. 
I guess the reason I assumed it worked like that was that the list of extended attributes in an msp xml file is the custom fields that are in use. At least it seems to be.

What would you recommend to get the list of "in use" task fields? Would I have to iterate through all the custom fields for each task?

The reason I want to get this list is that in our application we want to allow the user to map custom fields from an imported file to specific fields in our application. To do the mapping we show the user a list of all available custom fields from the file. But we don't want to show the fields that are not "in use". 

Hope this makes sense.

Kind Regards
Fred

**Comment by joniles** [comment] 2020-11-18 14:00
OK, so I've added a new method called `getPopulatedFields` to the `TaskContainer`, `ResourceContainer` and `ResourceAssignmentContainer` classes (these are the objects you get if you call `project.getTasks()`, `project.getResources()` etc).

As the name suggests, these methods will determine which fields have been populated across the whole project for each entity type. This covers _all_ fields in each object (not just custom fields), but it's giving you a `Set` back so it's easy enough to do a `contains` operation, or even an intersection if you want to create your own `Set` with the fields you are interested in (you may find the `TaskFieldLists`, `ResourceFieldLists` and `AssignmentFieldLists` classes helpful if you want to create a set of, for example, "all task custom fields").

**Comment by fdahlberg** [comment] 2020-11-23 08:55
Thanks for this. I think I understand how this works. I'll try it out as soon as the new version is out. 
Fred

**Comment by joniles** [comment] 2020-11-24 11:50
Just to let you know that the new version is now available.

**Comment by fdahlberg** [comment] 2020-11-24 12:30
Thanks Jon!

**Comment by fdahlberg** [comment] 2020-12-02 14:57
HI Jon,
Finally found some time to test out this new functionality. For an msp xml file the getPopulatedFields seems to work really well. When I import an .mpp file however getPopulatedFields retuns all the fields. Doesn't seem right, or is that expected?
Fred

**Comment by joniles** [comment] 2020-12-07 10:50
Ah! That's an interesting problem. The issue stems from data in an MPP file which is held in fixed blocks, so the attributes these blocks contain always have a value, even if one hasn't been supplied by a user. I've updated the getPopulatedFields methods so that they ignore fields which just contain default values (e.g. zero costs, zero durations). This should give you a more manageable set of fields to work with. The change will be in the next version of MPXJ.

**Comment by fdahlberg** [comment] 2020-12-07 12:42
Sounds very good!
