### ISSUE TITLE
resource.Type returns "work" for Material resource

### ISSUE THREAD

**Issue by ConstructionProject** [joniles/mpxj#57] opened 2018-08-21 12:53 UTC
MPXJ 7.6.0 (net.sf.mpxj-for-vb)  
"WORK" net.sf.mpxj.resource.type  is returned for material resources .

**Comment by joniles** [comment] 2018-08-21 13:46
Could you provide a sample file which demonstrates this?

**Comment by ConstructionProject** [comment] 2018-08-22 10:02
Hi Jon  !

Sorry, I was wrong with 1 topic in prev letter. Forgot to change resource
type in example attached.
Type mismatch probably occurs in my local (ukrainian)  version. I check it
and write if find something.

2 topic (resource custom fields) is valid.



Vadim Gerya, PMP
Project Management Profy LLC


вт, 21 авг. 2018 г. в 16:46, Jon Iles <notifications@github.com>:

**Comment by ConstructionProject** [comment] 2018-08-29 22:42
Hi Jon!
Sorry for late response I decided to make some complex tests and send you
all I found at once. Hope this helps.
You may find me at SKYPE *vgerya * if details required.
Project .mpp sample is attached and if it is not arrived you may get it
from share
https://drive.google.com/drive/folders/1tO75afu-CTz2Zw3_k6MG7QOAs9-TkbuY
Environment:  MSProject 2013 (2016), MPXJ 7.6.1 installed from NuGet into
VS2017   (net.sf.mpxj-for-vb, net.sf.mpxj-common, net.sf.mpxj-ikvm)
Used MPReader in way like (VB sample):
*Dim readerMPP As MPPReader = New MPPReader()*

*readerMPP.UseRawTimephasedData = True*

*Dim projectFileMPP As MPXJ.ProjectFile  = readerMPP.read(Path)*

*1)  For assignment (MPXJ.ResourceAssignment, MPXJ = net.sf.mpxj)  *
a) .getFlag(index) does not return correct value.  Look at ResourceUsage
View in MPXJ_test5_to_JonIles.mpp. Flag1,2, 10 set for some assignments bur
is not returned by   .getFlag(1)..(2) (10)
b) .getText(index) does not return values if  LookupTable is assigned to
Text field/. Look at Tex1(ResCode) (ResourceUsage View
in MPXJ_test5_to_JonIles.mpp.)
*2) For TimephasedData (I checked it for UseRawTimephasedData = True and
False, doesnt matter) *
 java.util.list returned by ResourceAssignment.TimephasedWork
contains  TimephasedItem which has Start and Finish out of  ResourceAssignment
Start|Finish range.
Look at  Task1|Subcon1  assignment (taskUniquieID= 1, ResUniquieD=3) in the
same file.
All 3 listitems contain wrong data but 2 an 3 has finish dates later then
assignment finish.
TimephasedWork  for  Task1|Res2Material  assignment (taskUniquieID= 1,
ResUniquieD=2) is also not correct from "per day" point of view (only 1
item with wrong finish) .
*3) Resource Type mismatch.*
 Returns WORK Resource.Type for material resource.
Please look at  second file (C-ProjectDemo_EN.mpp) in attachment.
SubContractor 1, SubContractor 2, CUSTOMER are material resources but MPXJ
Resource.Type returns WORK.

4)  I see Resource OullineCodes problem ( no CustomFieldValueItem(s)
existed in LookupTable ) has been solved  in 7.6.1 version. I wrote about
in previous letter.

If any demonsrtation/explanations/details required - please call my SKYPE
above.
Thanks a lot for developing and supporting MPXJ !

Vadim Gerya, PMP reMVP on MSProject ,
Project Management Profy LLC
www.pmf.kiev.ua ,  www,cproject.pro
UKRAINE, Kiev


ср, 22 авг. 2018 г. в 12:23, Jon Iles <notifications@github.com>:

**Comment by ConstructionProject** [comment] 2018-09-05 17:47
Any News ?

**Comment by ndarlington** [comment] 2018-10-17 16:46
I do get the same thing too - both Material and Work resources are coming in from the .mpp as Type Work (1).

Cost resources come in as Type Cost (2).

[material-converts-to-work.zip](https://github.com/joniles/mpxj/files/2488388/material-converts-to-work.zip)

Using the same sample code I gave for #64 to take a .mpp and write to .xml I have attached the project files.

The .mpp has 1 resource of each type ("mat" being the material resource).

Checking in-memory after reading in the .mpp the resource type has changed for the material resource (and so writes it out as a work resource too).

**Comment by ndarlington** [comment] 2018-10-17 16:49
Most of my work is in Mpxj 7.6.2 for .Net and that's where I saw the problem, but the above projects attached were only touched and converted by the java implementation, not the .Net one, so the issue is the same there too.

**Comment by ndarlington** [comment] 2018-10-18 05:14
This looks to be where the ResourceType.MATERIAL is being overwritten / reset to ResourceType.WORK:
https://github.com/joniles/mpxj/blob/d8b586c9b69f34bc738c9ec1e06ab31079de72fa/src/net/sf/mpxj/mpp/MPP14Reader.java#L1688-L1691

Here it is on the verge of being changed for the project file attached above.
![image](https://user-images.githubusercontent.com/40403963/47132407-52f53200-d269-11e8-8982-acbeedf82451.png)

Which is probably something we cannot work around by changing their workgroup, per the final statement at https://support.office.com/en-us/article/Workgroup-resource-field-d5705f77-672f-4981-8e7c-91d44cc59754
> The Workgroup field is not available for material resources.

**Comment by joniles** [comment] 2018-10-22 07:50
Hi,

I'm pleased to say that the code now on GitHub contains a fix for this issue. This will be available in the next release of MPXJ.

Jon

**Closed by joniles** 2018-10-22 07:50 UTC
